name: github-actions
run-name: ${{ github.actor }} is launching GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Test with unittest
        run: |
          ls
          pwd
          python -m unittest discover -s ./tests  -p 'test_*.py'